variables:   
  FORCE_COLOR: "1" 
        
stages:  
  - cloneBuild   

# Template de clone 
.cloneBuild: &cloneBuild 
- echo "Removendo as pastas do repo" 
- rm -rf ezops-teste-higorsilva 
- echo "Clone do repo do apischedulefix" 
- git clone https://gitlab.com/higorsilva707/ezops-test-higorsilva.git
- echo "Entrando na pasta de instalacao do API"
- pwd  
- cd /ezops-teste-higorsilva/nodejs/
- echo "Entrando na pasta de instalacao do API"
- echo "Build do Dockerfile"
- docker build -t higorsilva/node-web-app .
- echo "Run do container"
- docker run -p 3000:3000 -d higorsilva/node-web-app

gitclone:
  stage: cloneBuild
  script:
    - *cloneBuild
  only:
    - /^master$/
  tags:
    - docker-ezopsteste

